name: Deploy Hardhat to Devnet & run tests

on:
  pull_request:
    types: 
      - closed

jobs:
  deploy-and-build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DockerHub credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Pull Docker image
        run:
          docker pull mtotovski/go-ethereum:latest

      - name: Run image container
        run: |
          docker run -d --name geth-devnet -p 8545:8545 -p 8546:8546 mtotovski/go-ethereum:latest \
            --dev --http --http.addr 0.0.0.0 --http.port 8545 \
            --http.api personal,db,eth,net,web3 --dev.period 5

      - name: Copy Hardhat files to containerethereum
        run: |
          docker exec geth-devnet mkdir -p /go-ethereum/hardhat
          docker cp hardhat/. geth-devnet:/go-ethereum/hardhat
          docker exec geth-devnet ls -l /go-ethereum/hardhat
          
      - name: Install Node.js and npm in container
        run: docker exec geth-devnet apk add --no-cache nodejs npm

      - name: Install Hardhat dependencies
        run: docker exec geth-devnet sh -c "cd /go-ethereum/hardhat && npm install"

      - name: Run Hardhat tests
        run: docker exec geth-devnet sh -c "cd /go-ethereum/hardhat && npx hardhat test"

      - name: Build new Docker image
        run: |
          docker commit geth-devnet go-eth-hardhat:latest
          docker tag go-eth-hardhat:latest mtotovski/go-ethereum-devnet:latest

      - name: Push new Docker image
        run: docker push mtotovski/go-ethereum-devnet:latest
