name: Deploy Hardhat to Devnet

on:
  pull_request:
    types: 
      - closed

jobs:
  deploy-and-build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DockerHub credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:contracts-deployed

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy Hardhat Contracts
        working-directory: ./hardhat
        run: |
          npm install
          npx hardhat compile
          npx hardhat run scripts/deploy.js

      - name: Start local devnet container
        run: |
            docker pull ${{ env.DOCKERHUB_REPO }}:contracts-deployed
            docker run -d -p 8545:8545 -p 8546:8546 -p 8547:8547 -p 30303:30303 --name devnet-test ${{ env.DOCKERHUB_REPO }}:contracts-deployed

      # - name: Run Hardhat tests against devnet
      #   working-directory: ./hardhat
      #   run: npm run test